# Generated by Django 3.2.4 on 2024-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('company', models.IntegerField(blank=True, default=0)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
