# Generated by Django 3.2.4 on 2024-03-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollconcept',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
