# Generated by Django 3.2.4 on 2024-03-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='TransferBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('bank', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField(blank=True, default=0)),
                ('type_concept', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAccountingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField()),
                ('type_concept', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollperiod')),
            ],
        ),
    ]
