# Generated by Django 3.2.4 on 2024-03-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0002_payrollaccountingtransaction_payrolldeduction_transferbank_transfercash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField(blank=True, default=0)),
                ('type_concept', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollperiod')),
            ],
        ),
    ]
