# Generated by Django 3.2.4 on 2024-03-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0003_payrollincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=0)),
                ('date_generated', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollperiod')),
            ],
        ),
    ]
