# Generated by Django 3.2.4 on 2024-03-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0004_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('employee', models.IntegerField(default=0)),
                ('company', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=100)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('public_holiday', models.BooleanField(default=False)),
                ('sales', models.IntegerField()),
                ('production', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payrollperiod')),
            ],
        ),
    ]
