# Generated by Django 3.2.4 on 2024-03-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.CharField(choices=[('BANRURAL', 'Banrural'), ('BANCO INDUSTRIAL', 'Banco Industrial'), ('G&T CONTINENTAL', 'G&T Continental'), ('BAM', 'Banco Agromercantil'), ('BAC', 'Banco de América Central')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='method_payment',
            field=models.CharField(choices=[('BANCO', 'Banco'), ('CHEQUE', 'Cheque'), ('EFECTIVO', 'Efectivo')], max_length=100),
        ),
    ]
