# Generated by Django 3.2.4 on 2024-03-21 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.CreateModel(
            name='SalaryIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_increase_employee', to='employee.employee')),
            ],
        ),
    ]
